version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PWD}

  mongo-express:
    depends_on:
      - "mongo"
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PWD}

  flask:
    depends_on:
      - "mongo"
    build:
      context: .
      target: ${ENV:-prod}
    container_name: flask
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PWD=${MONGO_DB_PWD}
      - APP_PORT=${APP_PORT}
